---
- hosts: 192.168.124.32 
  tasks:
    - shell: whoami
      register: out
    - debug: var=out
    - shell: whoami
      become_user: jboss
      become: yes
      register: out
    - debug: var=out
