---
- hosts: all
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
    - shell: cat ./append_here
    - lineinfile:
        path: ./append_here
        insertafter: EOF
        line: "{{ user_limit }}"
        state: present
    - shell: cat ./append_here
